version: "3.9"
services: 
    adguardhome:
        image: adguard/adguardhome
        container_name: adguardhome
        ports: 
            - 53:53/tcp
            - 53:53/udp
            - 82:82/tcp
            - 3000:3000/tcp
        volumes: 
            - ../luna_data/adguardhome/work:/opt/adguardhome/work
            - ../luna_data/adguardhome/conf:/opt/adguardhome/conf
        restart: unless-stopped

