version: "3.9"
services: 
    adguardhome:
        image: adguard/adguardhome
        container_name: adguardhome
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 82:82/tcp
            - 3000:3000/tcp
        volumes:
            - /home/pi/luna_data/adguardhome/work:/opt/adguardhome/work
            - /home/pi/luna_data/adguardhome/conf:/opt/adguardhome/conf
        restart: unless-stopped

    jellyfin:
        image: ghcr.io/linuxserver/jellyfin
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /home/pi/luna_data/jellyfin/cache:/cache
            - /home/pi/luna_data/jellyfin/config:/config
            - /mnt/ext_drive/luna_library/media:/media
        ports:
            - 8096:8096
        restart: unless-stopped

    airplay:
        image: mikebrady/shairport-sync
        container_name: airplay
        network_mode: host
        devices:
            - "/dev/snd:/dev/snd"
        volumes:
            - /home/pi/luna_data/airplay/shairport-sync.conf:/etc/shairport-sync.conf
        restart: unless-stopped

    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/pi/luna_data/portainer/data:/data
        restart: unless-stopped

    qbittorrent:
        image: ghcr.io/linuxserver/qbittorrent
        container_name: qbittorrent
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - WEBUI_PORT=8080
        volumes: 
            - /home/pi/luna_data/qbittorrent/config:/config
            - /mnt/ext_drive/luna_library/torrents:/data/torrents
        ports: 
            - 6881:6881
            - 6881:6881/udp
            - 8080:8080
        restart: unless-stopped

    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - AUTO_UPDATE=true
        volumes: 
            - /home/pi/luna_data/jackett/config:/config
            - /mnt/ext_drive/luna_library/torrents:/data/torrents
        ports:
            - 9117:9117
        restart: unless-stopped
    
    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /home/pi/luna_data/sonarr/config:/config
            - /mnt/ext_drive/luna_library:/data
        ports:
            - 8989:8989
        restart: unless-stopped

    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /home/pi/luna_data/radarr/config:/config
            - /mnt/ext_drive/luna_library:/data
        ports:
            - 7878:7878
        restart: unless-stopped

    flaresolverr:
        image: flaresolverr/flaresolverr
        container_name: flaresolverr
        environment: 
            - LOG_LEVEL=info
        ports:
            - 8191:8191
        restart: unless-stopped

