version: "3.9"
services: 
    jellyfin:
        image: ghcr.io/linuxserver/jellyfin
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /home/pi/luna_data/jellyfin/cache:/cache
            - /home/pi/luna_data/jellyfin/config:/config
            - /mnt/ext_drive/luna_library/media:/media
        ports:
            - 8096:8096
        restart: unless-stopped

