version: "3.9"
services: 
    qbittorrent:
        image: ghcr.io/linuxserver/qbittorrent
        container_name: qbittorrent
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - WEBUI_PORT=8080
        volumes: 
            - /home/pi/luna_data/qbittorrent/config:/config
            - /mnt/ext_drive/luna_library/torrents:/data/torrents
        ports: 
            - 6881:6881
            - 6881:6881/udp
            - 8080:8080
        restart: unless-stopped

    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - AUTO_UPDATE=true
        volumes: 
            - /home/pi/luna_data/jackett/config:/config
            - /mnt/ext_drive/luna_library/torrents:/data/torrents
        ports:
            - 9117:9117
        restart: unless-stopped
    
    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /home/pi/luna_data/sonarr/config:/config
            - /mnt/ext_drive/luna_library:/data
        ports:
            - 8989:8989
        restart: unless-stopped

    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        environment: 
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /home/pi/luna_data/radarr/config:/config
            - /mnt/ext_drive/luna_library:/data
        ports:
            - 7878:7878
        restart: unless-stopped

    flaresolverr:
        image: flaresolverr/flaresolverr
        container_name: flaresolverr
        environment: 
            - LOG_LEVEL=info
        ports:
            - 8191:8191
        restart: unless-stopped

